
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
  post: 5432
  host: 127.0.0.1
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: healthcare_development

test:
  <<: *default
  database: healthcare_test

production:
  <<: *default
  database: healthcare_production
  username: healthcare
  password: <%= ENV["HEALTHCARE_DATABASE_PASSWORD"] %>
