
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["HEALTHCARE_DATABASE_USERNAME"] || "root" %>
  password: <%= ENV["HEALTHCARE_DATABASE_PASSWORD"] || "root" %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || '3306' %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: healthcare_development

test:
  <<: *default
  database: healthcare_test

production:
  <<: *default
  database: healthcare_production
  username: <%= ENV["HEALTHCARE_DATABASE_USERNAME"] %>
  password: <%= ENV["HEALTHCARE_DATABASE_PASSWORD"] %>
